image: registry.gitlab.com/addictedcoders/tdb-app

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - build
  - deploy

build:
  stage: build
  script: 
    - npm install
    - npm run build
    - mkdir -p heroku/public
    - cp dist/* heroku/public
    - cp package.json heroku
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - node_modules
  artifacts:
    paths:
      - heroku

deploy_staging:
  stage: deploy
  dependencies:
    - build
  script:
    - cd CI_PROJECT_DIR/heroku
    - heroku git:remote $HEROKU_APP_NAME
    - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
  environment:
    name: tdb-app-staging
    url: https://tdb-app.herokuapp.com/
  only:
  - master  