image: addictedcoders/tdb-app

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - build
  - deploy

build:
  stage: build
  script: npm install && poi build
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - node_modules
  artifacts:
    paths:
      - dist

deploy_staging:
  stage: deploy
  script:
    - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
  environment:
    name: tdb-app-staging
    url: https://tdb-app.herokuapp.com/
  only:
  - master  