image: registry.gitlab.com/addictedcoders/tdb-app

stages:
  - build
  - deploy

build:
  stage: build
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - node_modules
  script: 
    - yarn install
    - npm test
    - $CI_PROJECT_DIR/upload.sh -p tdb-app -t $CI_COMMIT_REF_NAME@$CI_PIPELINE_ID
    - API_URL=https://tdb-service.herokuapp.com/api npm run build:prod
    - mkdir -p heroku/public
    - cp public/* heroku/public
    - cp static.json heroku
  artifacts:
    paths:
      - heroku

deploy_staging:
  stage: deploy
  script:
    - cd $CI_PROJECT_DIR/heroku
    - git init
    - git config user.name $HEROKU_GIT_USER_NAME
    - git config user.email $HEROKU_GIT_USER_EMAIL
    - heroku git:remote $HEROKU_APP_NAME
    - git add -A && git commit -m $CI_JOB_ID
    - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master -f
  environment:
    name: tdb-app-staging
    url: https://tdb-app.herokuapp.com/
  only:
    - master