language: node_js
node_js:
  - "8.9.3"

cache:
  yarn: true  

script: 
  - npm test
  - $TRAVIS_BUILD_DIR/upload.sh -p tdb-app -t $TRAVIS_BRANCH@$TRAVIS_BUILD_NUMBER
  - sed "s/http:\/\/localhost:8080\/api/https:\/\/tdb-service.herokuapp.com\/api/g" env.js -i
  - npm run build:prod

before_deploy:
  - mkdir -p heroku/public
  - cp public/* heroku/public

deploy:
- provider: script
  script: deployment/to_heroku.sh develop
  on:
    branch: develop
  skip_cleanup: true  
- provider: script
  script: deployment/to_heroku.sh master
  on:
    branch: master
  skip_cleanup: true    
