language: node_js
node_js:
  - "8.9.3"

cache:
  yarn: true  

script: 
  - npm test
  - $TRAVIS_BUILD_DIR/upload.sh -p tdb-app -t $TRAVIS_BRANCH@$TRAVIS_BUILD_NUMBER
  - API_URL=https://tdb-service.herokuapp.com/api npm run build:prod

before_deploy:
  - mkdir -p heroku/public
  - cp public/* heroku/public

deploy:
  skip_cleanup: true
  - provider: script
    script: deployment/to_heroku.sh
    on: 
      branch: master
  - provider: script
    script: deployment/to_heroku_staging.sh
    on: 
      branch: develop    